pipeline:
  identifier: Build_srikanthlahanday_SpringJavaDemo_1736326201837
  name: Build SpringJavaDemo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1736242057608
        repoName: srikanthlahanday/SpringJavaDemo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      mvn clean install
                      echo $(pwd)
              - step:
                  type: Owasp
                  name: Owasp_1
                  identifier: Owasp_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: target/my-app-1.0-SNAPSHOT.jar
                      detection: auto
                    advanced:
                      log:
                        level: info
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec: {}
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
