pipeline:
  identifier: Build_srikanthlahanday_SpringJavaDemo_1736326201837
  name: Build SpringJavaDemo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1736242057608
        repoName: srikanthlahanday/SpringJavaDemo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Welcome msg
                  spec:
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: mvn clean verify install
              - step:
                  type: Owasp
                  name: Owasp_1
                  identifier: Owasp_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
